controller:
  config:
  nodeSelector:
    agentpool: "nodepool2"
  replicaCount: "1"
  ingressClass: "nginx"
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

defaultBackend:
  nodeSelector:
    agentpool: "nodepool2"
