controller:
  config:
    enable-real-ip: true
  nodeSelector:
    agentpool: "nodepool2"
  replicaCount: "1"
  ingressClass: "nginx"
  service:
    externalTrafficPolicy: "Local"
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

defaultBackend:
  nodeSelector:
    agentpool: "nodepool2"
