controller:
  config:
  nodeSelector:
    agentpool: "nodepool2"
  replicaCount: "1"
  ingressClass: "nginx"
  service:
    externalTrafficPolicy: "Local"
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: "guestbook"
defaultBackend:
  nodeSelector:
    agentpool: "nodepool2"
